# Generated by Django 4.0 on 2021-12-19 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flutterwave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='payment_status',
        ),
    ]
